### ISSUE TITLE
Snyk fails to detect sbt-dependency-graph and uses legacy mode whenever sbt-scalafix plugin in present

### ISSUE THREAD

**Issue by joelittlejohn** [snyk/snyk-sbt-plugin#86]
- `sbt -v` = `sbt 1.3.13 (AdoptOpenJDK Java 1.8.0_242)`

- What command was run(including all the options):

`snyk test`

### Expected behaviour

sbt-dependency-graph should be detected and used.

### Actual behaviour

sbt-dependency-graph is not used and instead Snyk falls back to legacy mode.

The following message is shown:

```
Please make sure that the `sbt-dependency-graph` plugin (https://github.com/jrudolph/sbt-dependency-graph) is installed globally or on the current project, and that `sbt "-Dsbt.log.noformat=true" dependencyTree` executes successfully on this project.

Alternatively you can use `sbt-coursier` for dependency resolution (https://get-coursier.io/docs/sbt-coursier), in which case ensure that the plugin is installed on the current project and that `sbt "-Dsbt.log.noformat=true" coursierDependencyTree` executes successfully on this project.

For this project we guessed that you are using sbt-dependency-graph.

If the problem persists, collect the output of `sbt "-Dsbt.log.noformat=true" dependencyTree` or `sbt "-Dsbt.log.noformat=true" coursierDependencyTree` and contact support@snyk.io
```

By running `snyk test -d` you can see the following:

```
  snyk-sbt-plugin [error] sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime. +5s
  snyk-sbt-plugin  +0ms
  snyk-sbt-plugin [error] setting(ScopedKey(Scope(Select(ProjectRef(file:/Users/joelittlejohn/workspace/test/,root)), Zero, Zero, Zero),snykExtractProjectData)) at LinePosition((snyk.SnykSbtPlugin.projectSettings) tmp-53169NGCS5KiOlLWJ-SnykSbtPlugin.scala,82) referenced from ScopedKey(Scope(Select(ProjectRef(file:/Users/joelittlejohn/workspace/test/,root)), Select(ConfigKey(scalafix)), Zero, Zero),moduleGraph) +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.Init.sbt$internal$util$Init$$handleUndefined(Settings.scala:693) +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.Init$Bind.$anonfun$validateKeyReferenced$3(Settings.scala:785) +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.Init$Bind.evaluate(Settings.scala:780) +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.Init$$anon$13.apply(Settings.scala:705) +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.Init$$anon$13.apply(Settings.scala:705) +0ms
  snyk-sbt-plugin  +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.AList$$anon$4.transform(AList.scala:87) +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.Init$Apply.evaluate(Settings.scala:852) +0ms
  snyk-sbt-plugin [error] 	at sbt.std.FullInstance$.$anonfun$flatten$2(TaskMacro.scala:70) +0ms
  snyk-sbt-plugin [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49) +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62) +0ms
  snyk-sbt-plugin [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67) +0ms
  snyk-sbt-plugin [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281) +0ms
  snyk-sbt-plugin [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19) +0ms
  snyk-sbt-plugin [error] 	at sbt.Execute.work(Execute.scala:290) +1ms
  snyk-sbt-plugin [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281) +0ms
  snyk-sbt-plugin [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178) +0ms
  snyk-sbt-plugin [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37) +0ms
  snyk-sbt-plugin [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) +0ms
  snyk-sbt-plugin [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) +0ms
  snyk-sbt-plugin [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) +0ms
  snyk-sbt-plugin [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) +0ms
  snyk-sbt-plugin [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) +0ms
  snyk-sbt-plugin [error] 	at java.lang.Thread.run(Thread.java:748) +0ms

  ...

  snyk-sbt-plugin Falling back to legacy inspect +1ms
```

### Steps to reproduce

1. Create a new scala project like `sbt new scala/scala-seed.g8`
2. Add the following to `project/plugins.sbt`:

        addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
        addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.19")

3. Run `snyk test`

**Comment by joelittlejohn** [comment]
Another one to be added here I guess:

https://github.com/snyk/snyk-sbt-plugin/blob/master/scala/SnykSbtPlugin-1.2x.scala#L11

**Comment by lili2311** [comment]
👋 Please can you please share the output of ``sbt "-Dsbt.log.noformat=true" dependencyTree``  as per error message to validate this command can succeed for you?

**Comment by MegaBean** [comment]
Hello! Is it ok to close this, since we are tracking this issue in our support queue? It will be easier for us to keep all communication in one place...

**Comment by joelittlejohn** [comment]
@lili2311 Here's the output:
```
$ sbt "-Dsbt.log.noformat=true" dependencyTree
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 1.8.0_242)
[info] loading settings for project foo-build from plugins.sbt ...
[info] loading project definition from /Users/joelittlejohn/workspace/foo/project
[info] Compiling 1 Scala source to /Users/joelittlejohn/workspace/foo/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] loading settings for project root from build.sbt ...
[info] set current project to foo (in build file:/Users/joelittlejohn/workspace/foo/)
[info] com.example:foo_2.13:0.1.0-SNAPSHOT [S]
[success] Total time: 0 s, completed 28-Sep-2020 14:39:26
```

I've given the steps to reproduce, so feel free create your own project and run this kind of command yourself.

@MegaBean Sure - I'll update here when a fix is available to help anyone else that finds this ticket. Any idea when a fix will be deployed?
